<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260211095529 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE championnat (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, competition_id_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AB8C2208CF3AC81 ON championnat (competition_id_id)');
        $this->addSql('CREATE TABLE competition (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, epreuve_id_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B50A2CB1E459249A ON competition (epreuve_id_id)');
        $this->addSql('CREATE TABLE epreuve (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, sport_id_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D6ADE47FCB38FF4E ON epreuve (sport_id_id)');
        $this->addSql('CREATE TABLE sport (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE championnat ADD CONSTRAINT FK_AB8C2208CF3AC81 FOREIGN KEY (competition_id_id) REFERENCES competition (id)');
        $this->addSql('ALTER TABLE competition ADD CONSTRAINT FK_B50A2CB1E459249A FOREIGN KEY (epreuve_id_id) REFERENCES epreuve (id)');
        $this->addSql('ALTER TABLE epreuve ADD CONSTRAINT FK_D6ADE47FCB38FF4E FOREIGN KEY (sport_id_id) REFERENCES sport (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE championnat DROP CONSTRAINT FK_AB8C2208CF3AC81');
        $this->addSql('ALTER TABLE competition DROP CONSTRAINT FK_B50A2CB1E459249A');
        $this->addSql('ALTER TABLE epreuve DROP CONSTRAINT FK_D6ADE47FCB38FF4E');
        $this->addSql('DROP TABLE championnat');
        $this->addSql('DROP TABLE competition');
        $this->addSql('DROP TABLE epreuve');
        $this->addSql('DROP TABLE sport');
    }
}
